services:
  - type: web
    name: wills-bot-2.0
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OWNER_NUMBER
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: PREFIX
        value: "!"
      - key: RENDER_API_KEY
        sync: false
      - key: RENDER_SERVICE_ID
        sync: false
      - key: SESSION_DATA
        sync: false
      - key: NODE_VERSION
        value: "20"
